### ISSUE TITLE
Specify old version in PR title

### ISSUE THREAD

**Issue by rany2** [flathub-infra/flatpak-external-data-checker#311] opened 2022-06-24 19:18 UTC
I've noticed that FEDC sometimes creates PRs that downgrade the package (probably from a caching issue on the mirror's end). In this issue I'm proposing that the PR title/body be modified to specify the old version and the new version it's getting bumped to.

Example:

*  Update chromium-101.0.4951.54.tar.xz from 101.0.4951.54 to 101.0.4951.64

**Comment by rany2** [comment] 2022-06-24 19:19
This issue happens mostly in the Brave flatpak though, I think it might be better to add a check to make sure that the PR is upgrading and not downgrading  instead.

**Comment by gasinvein** [comment] 2022-06-24 19:24
The problem is, f-e-d-c doesn't know what the current version is - there is no such information stored in the manifest currently.
Kinda duplicate of #286, I'll rename and pin that one as a more generic issue.

**Closed as not planned by gasinvein** 2022-06-24 19:24 UTC
