### ISSUE TITLE
Git checker should extract timestamp

### ISSUE THREAD

**Issue by darkdragon-001** [flathub-infra/flatpak-external-data-checker#295] opened 2022-04-24 12:13 UTC
Git checker should extract timestamp from git tag.

Currently, there is `Timestamp: None`:
```
OUTDATED: boost.git
 Has a new version:
  URL:       https://github.com/boostorg/boost.git
  Commit:    5df8086b733798c8e08e316626a16babe11bd0d2
  Tag:       boost-1.79.0
  Branch:    None
  Version:   1.79.0
  Timestamp: None
```

**Comment by gasinvein** [comment] 2022-04-24 12:34
Duplicate of #154

**Closed as completed by gasinvein** 2022-04-24 12:34 UTC
